In [1]:
import pandas as pd

views = pd.read_csv(
    '../data/feed-views.log',
    sep = '\t',
    names=["datetime", "user"]
)

In [2]:
views['datetime'] = pd.to_datetime(views['datetime'])

In [3]:
views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views['day'] = views['datetime'].dt.day
views['hour'] = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

In [4]:
views.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1076 entries, 0 to 1075
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1076 non-null   datetime64[ns]
 1   user      1076 non-null   object
 2   year      1076 non-null   int32
 3   month     1076 non-null   int32
 4   day       1076 non-null   int32
 5   hour      1076 non-null   int32
 6   minute    1076 non-null   int32
 7   second    1076 non-null   int32
dtypes: datetime64[ns](1), int32(6), object(1)
memory usage: 42.2+ KB

In [5]:
bins = [0, 4, 7, 11, 17, 20, 24]

labels = [
    "night",          
    "early morning",
    "morning",        
    "afternoon",      
    "early evening",  
    "evening",       
]

views['daytime']= pd.cut(
    views['hour'],
    bins = bins,
    labels = labels,
    right = False,
    include_lowest=True
)

In [6]:
views = views.set_index('user')

In [7]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [8]:
views['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [9]:
views = views.sort_values(by=['hour', 'minute', 'second'])

In [10]:
views['hour'].min()

np.int32(0)

In [11]:
views['hour'].max()

np.int32(23)

In [12]:
views[views['daytime'] == 'night']['hour'].max()

np.int32(3)

In [13]:
views[views['daytime'] == 'morning']['hour'].min()

np.int32(8)

In [14]:
views[
    (views['daytime'] == 'night') &
    (views['hour'] == views[views['daytime']=='night']['hour'].max())
]

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night
konstantin,2020-04-19 03:23:55.473926,2020,4,19,3,23,55,night
konstantin,2020-04-19 03:33:07.757714,2020,4,19,3,33,7,night

In [15]:
views['hour'].mode()

0    22
Name: hour, dtype: int32

In [16]:
views['daytime'].mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

In [17]:
views.nsmallest(3, 'hour')
views.nlargest(3, 'hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
ekaterina,2020-05-14 23:02:11.327532,2020,5,14,23,2,11,evening
ekaterina,2020-05-14 23:02:14.494985,2020,5,14,23,2,14,evening
ekaterina,2020-05-14 23:02:15.588808,2020,5,14,23,2,15,evening

In [18]:
desc = views.describe()
iqr = desc.loc['75%', 'hour'] - desc.loc['25%', 'hour']
desc

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [19]:
iqr

np.float64(9.0)